baseURL = 'https://sethbaird01.github.io/'
locale = 'en-us'
title = 'sbaird.net'
theme = 'hugo-xmin'
ignoreFiles = [ "\\.Rmd$", "\\.Rmarkdown$", "_cache$" ]
footnotereturnlinkcontents = "↩"
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
  name = "Home"
  url = ""
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "projects"
  weight = 1

[[menu.main]]
name = "Posts"
url = "posts"
weight = 2

[[menu.main]]
  name = "Photos"
  url = "photos"
  weight = 3


[params]
  footer = '&copy; [Seth Baird](https://sbaird.net) {Year} | [Github](https://github.com/sethbaird01) | [LinkedIn](https://www.linkedin.com/in/sethbaird01/)'

[security]
allowContent = [ ".*" ]

[markup.highlight]
codeFences = false